# Generated by Django 3.1.7 on 2021-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcommitte',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='committe_profile_pic'),
        ),
    ]
