# Generated by Django 3.1.7 on 2021-05-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shobhapoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('quotation', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='shobhapoti')),
            ],
        ),
    ]
